#define PROJECT_NAME "DNSTD"
#define PACKAGE "DNSTD"
#define PACKAGE_NAME "DNSTD"
#define PACKAGE_BUGREPORT "david@davecoss.com"

#define DNSTD_MAJOR_VERSION 2
#define DNSTD_MINOR_VERSION 3
#define VERSION "2.3"
#define PACKAGE_STRING PACKAGE_NAME " " VERSION

/* #undef BUILD_WITH_ZLIB */
